#ifndef TST_PLUGIN3GLOBAL_H
#define TST_PLUGIN3GLOBAL_H
#if defined(TST_PLUGIN3_LIBRARY)
#  define TST_PLUGIN3LIB Q_DECL_EXPORT
#else
#  define TST_PLUGIN3LIB Q_DECL_IMPORT
#endif
#endif // TST_PLUGIN3GLOBAL_H

