######################################################################
# Automatically generated by qmake (2.01a) ?? 25. ??? 15:05:28 2011
######################################################################
include(../plugins.pri)
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lplugin -ltreedockwidget -lmdiextarea -lmainwindow
# Input
HEADERS += exampleplug.h \
    exampleglobal.h
SOURCES += exampleplug.cpp
RESOURCES += \
    example.qrc
