#ifndef STACKEDITINGGLOBAL_H
#define STACKEDITINGGLOBAL_H
#if defined(STACKEDITING_LIBRARY)
#  define STACKEDITINGLIB Q_DECL_EXPORT
#else
#  define STACKEDITINGLIB Q_DECL_IMPORT
#endif
#endif // STACKEDITINGGLOBAL_H

