#ifndef PUSHBUTTONIMAGEGLOBAL_H
#define PUSHBUTTONIMAGEGLOBAL_H
#if defined(PUSHBUTTONIMAGE_LIBRARY)
#  define PUSHBUTTONIMAGELIB Q_DECL_EXPORT
#else
#  define PUSHBUTTONIMAGELIB Q_DECL_IMPORT
#endif
#endif // PUSHBUTTONIMAGEGLOBAL_H

