include(../tst_plugin.pri)
CONFIG += plugin
TEMPLATE = lib
DEFINES +=  TST_PLUGIN3_LIBRARY

VERSION = 1.0.0
QMAKE_TARGET_COMPANY = "RTPTechGroup"
QMAKE_TARGET_PRODUCT = "TST_PLUGIN3"
QMAKE_TARGET_DESCRIPTION = "TST_PLUGIN3"
QMAKE_TARGET_COPYRIGHT = "Copyright (C) RTPTechGroup"

# Input
HEADERS   = *.h
SOURCES   = *.cpp
RESOURCES = *.qrc

