#ifndef CLIPBOARDSTACKGLOBAL_H
#define CLIPBOARDSTACKGLOBAL_H
#if defined(CLIPBOARDSTACK_LIBRARY)
#  define CLIPBOARDSTACKLIB Q_DECL_EXPORT
#else
#  define CLIPBOARDSTACKLIB Q_DECL_IMPORT
#endif
#endif // CLIPBOARDSTACKGLOBAL_H
