#ifndef DATABASEMODELGLOBAL_H
#define DATABASEMODELGLOBAL_H
#if defined(DATABASEMODEL_LIBRARY)
#  define DATABASEMODELLIB Q_DECL_EXPORT
#else
#  define DATABASEMODELLIB Q_DECL_IMPORT
#endif
#endif // DATABASEMODELGLOBAL_H
