#ifndef DATABASEMODELMANAGERGLOBAL_H
#define DATABASEMODELMANAGERGLOBAL_H
#if defined(DATABASEMODELMANAGER_LIBRARY)
#  define DATABASEMODELMANAGERLIB Q_DECL_EXPORT
#else
#  define DATABASEMODELMANAGERLIB Q_DECL_IMPORT
#endif
#endif // DATABASEMODELGLOBAL_H
