#ifndef MAINWINDOWS_GLOBAL_H
#define MAINWINDOWS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAINWINDOWS_LIBRARY)
#  define MAINWINDOWSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAINWINDOWSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAINWINDOWS_GLOBAL_H
