#ifndef TST_PLUGIN1GLOBAL_H
#define TST_PLUGIN1GLOBAL_H
#if defined(TST_PLUGIN1_LIBRARY)
#  define TST_PLUGIN1LIB Q_DECL_EXPORT
#else
#  define TST_PLUGIN1LIB Q_DECL_IMPORT
#endif
#endif // TST_PLUGIN1GLOBAL_H

