######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 11:31:24 2011
######################################################################

TARGET =
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lplugin
include(../app.pri)

# Input
#HEADERS +=
#FORMS +=
SOURCES += main.cpp
