######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 11:31:24 2011
######################################################################

DEPENDPATH += .
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION, 4) {
  QT += widgets
}
LIBS += -lplugin
include(../app.pri)

# Input
#HEADERS +=
#FORMS +=
SOURCES += main.cpp
